version: '3.8'

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:3000"
  backend:
    build: ./backend
    ports:
      - "8080:4000"
  
 